# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM python:3.9@sha256:61cb1ea441cba629934a49a384dcb501154746fa0139f601f4d733f7b956c359

EXPOSE 9000
WORKDIR /opt/storage-emulator

COPY google-cloud-cpp/google/cloud/storage/emulator /opt/storage-emulator/

RUN python3 -m pip install -r requirements.txt

CMD ["gunicorn", "--bind", "localhost:9000", "--worker-class", "sync", "emulator:run()"]
