# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 7200s  # 2 hours
steps:

# Fetch cached plt files
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', '-r', 'gs://$PROJECT_ID/elixir-artifacts/elixir*', '/workspace/plt_builder/plts/']
  id: load-plts
  waitFor: ['-']

# Elixir 1.4 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/elixir14', '--build-arg', 'BASE_IMAGE=elixir:1.4', '--build-arg', 'SHORT_VERSION=14', '.']
  id: elixir14-build
  waitFor: [load-plts]
- name: gcr.io/gcp-runtimes/container-structure-test
  args: ['test', '--image', 'gcr.io/$PROJECT_ID/elixir14', '--config', '/workspace/elixir14.yaml']
  id: elixir14-test
  waitFor: ['elixir14-build']
- name: gcr.io/$PROJECT_ID/elixir14
  args: ['/bin/bash', '-c', 'cp /root/.mix/*.plt /workspace/plt_builder/plts/elixir14']
  id: elixir14-extract-plts
  waitFor: ['elixir14-test']

# Elixir 1.5 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/elixir15', '--build-arg', 'BASE_IMAGE=elixir:1.5', '--build-arg', 'SHORT_VERSION=15', '.']
  id: elixir15-build
  waitFor: [load-plts]
- name: gcr.io/gcp-runtimes/container-structure-test
  args: ['test', '--image', 'gcr.io/$PROJECT_ID/elixir15', '--config', '/workspace/elixir15.yaml']
  id: elixir15-test
  waitFor: ['elixir15-build']
- name: gcr.io/$PROJECT_ID/elixir15
  args: ['/bin/bash', '-c', 'cp /root/.mix/*.plt /workspace/plt_builder/plts/elixir15']
  id: elixir15-extract-plts
  waitFor: ['elixir15-test']

# Elixir 1.6 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/elixir16', '--build-arg', 'BASE_IMAGE=elixir:1.6', '--build-arg', 'SHORT_VERSION=16', '.']
  id: elixir16-build
  waitFor: [load-plts]
- name: gcr.io/gcp-runtimes/container-structure-test
  args: ['test', '--image', 'gcr.io/$PROJECT_ID/elixir16', '--config', '/workspace/elixir16.yaml']
  id: elixir16-test
  waitFor: ['elixir16-build']
- name: gcr.io/$PROJECT_ID/elixir16
  args: ['/bin/bash', '-c', 'cp /root/.mix/*.plt /workspace/plt_builder/plts/elixir16']
  id: elixir16-extract-plts
  waitFor: ['elixir16-test']

# Elixir 1.7 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/elixir17', '--build-arg', 'BASE_IMAGE=elixir:1.7', '--build-arg', 'SHORT_VERSION=17', '.']
  id: elixir17-build
  waitFor: [load-plts]
- name: gcr.io/gcp-runtimes/container-structure-test
  args: ['test', '--image', 'gcr.io/$PROJECT_ID/elixir17', '--config', '/workspace/elixir17.yaml']
  id: elixir17-test
  waitFor: ['elixir17-build']
- name: gcr.io/$PROJECT_ID/elixir17
  args: ['/bin/bash', '-c', 'cp /root/.mix/*.plt /workspace/plt_builder/plts/elixir17']
  id: elixir17-extract-plts
  waitFor: ['elixir17-test']

# Elixir 1.8 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/elixir18', '--build-arg', 'BASE_IMAGE=elixir:1.8', '--build-arg', 'SHORT_VERSION=18', '.']
  id: elixir18-build
  waitFor: [load-plts]
- name: gcr.io/gcp-runtimes/container-structure-test
  args: ['test', '--image', 'gcr.io/$PROJECT_ID/elixir18', '--config', '/workspace/elixir18.yaml']
  id: elixir18-test
  waitFor: ['elixir18-build']
- name: gcr.io/$PROJECT_ID/elixir18
  args: ['/bin/bash', '-c', 'cp /root/.mix/*.plt /workspace/plt_builder/plts/elixir18']
  id: elixir18-extract-plts
  waitFor: ['elixir18-test']

# Elixir 1.9 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/elixir19', '--build-arg', 'BASE_IMAGE=elixir:1.9', '--build-arg', 'SHORT_VERSION=19', '.']
  id: elixir19-build
  waitFor: [load-plts]
- name: gcr.io/gcp-runtimes/container-structure-test
  args: ['test', '--image', 'gcr.io/$PROJECT_ID/elixir19', '--config', '/workspace/elixir19.yaml']
  id: elixir19-test
  waitFor: ['elixir19-build']
- name: gcr.io/$PROJECT_ID/elixir19
  args: ['/bin/bash', '-c', 'cp /root/.mix/*.plt /workspace/plt_builder/plts/elixir19']
  id: elixir19-extract-plts
  waitFor: ['elixir19-test']

# Push cached plt files
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', '-r', '/workspace/plt_builder/plts/elixir*', 'gs://$PROJECT_ID/elixir-artifacts/']
  waitFor: ['elixir14-extract-plts', 'elixir15-extract-plts', 'elixir16-extract-plts', 'elixir17-extract-plts', 'elixir18-extract-plts', 'elixir19-extract-plts']

timeout: 3600s
