# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:

# Java 7 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/java7', '.']
  dir: java7
  id: java7-build
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', 'gcr.io/$PROJECT_ID/java7', '--config', 'java7.yaml', '-v']
  waitFor: ['java7-build']

# Java 8 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/java8', '.']
  dir: java8
  id: java8-build
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', 'gcr.io/$PROJECT_ID/java8', '--config', 'java8.yaml', '-v']
  waitFor: ['java8-build']

# Java 9 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/java9', '.']
  dir: java9
  id: java9-build
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', 'gcr.io/$PROJECT_ID/java9', '--config', 'java9.yaml', '-v']
  waitFor: ['java9-build']

# Java 10 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/java10', '.']
  dir: java10
  id: java10-build
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', 'gcr.io/$PROJECT_ID/java10', '--config', 'java10.yaml', '-v']
  waitFor: ['java10-build']

# Java 11 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/java11', '.']
  dir: java11
  id: java11-build
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', 'gcr.io/$PROJECT_ID/java11', '--config', 'java11.yaml', '-v']
  waitFor: ['java11-build']

images:
- gcr.io/$PROJECT_ID/java7
- gcr.io/$PROJECT_ID/java8
- gcr.io/$PROJECT_ID/java9
- gcr.io/$PROJECT_ID/java10
- gcr.io/$PROJECT_ID/java11
