# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# note: /workspace is a special directory in the docker image where all the files in this folder
# get placed on your behalf

timeout: 7200s # 2 hours
steps:
    # Go 1.24 build
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/release-images/go124", "."]
    dir: go/go124-release
    id: go124-build
    waitFor: ["-"]
  - name: gcr.io/gcp-runtimes/structure_test
    args:
      [
        "-i",
        "us-central1-docker.pkg.dev/$PROJECT_ID/release-images/go124",
        "--config",
        "/workspace/go/go124.yaml",
        "-v",
      ]
    waitFor: ["go124-build"]

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/release-images/go124

options:
  logging: CLOUD_LOGGING_ONLY
